create database if not exists FINANCEIRO;
USE FINANCEIRO;

CREATE TABLE IF NOT EXISTS USUARIO_CADASTRO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_USUARIO VARCHAR(50) UNIQUE,
CADASTRO_NOME_COMPLETO VARCHAR (100) NOT NULL,
CADASTRO_NASC DATE NOT NULL,
PAIS VARCHAR(20),
ESTADO CHAR(2),
CADASTRO_EMAIL VARCHAR(20) NOT NULL UNIQUE,
DATA_CRIACAO_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
ATIVO BOOL NOT NULL DEFAULT TRUE);

CREATE TABLE  IF NOT EXISTS AUTENTICACAO(
ID_AUTENTICACAO INT   PRIMARY KEY AUTO_INCREMENT,
AUTENTICACAO_USUARIO INT NOT NULL,
SENHA_HASH VARCHAR(255) NOT NULL,
ULTIMO_LOGIN DATETIME DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_AUTEN_CADASTRO FOREIGN KEY(AUTENTICACAO_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE  CASCADE
ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS RECUPERA_SENHA(
ID_TOKEN INT AUTO_INCREMENT PRIMARY KEY,
RECUPERA_SENHA_USUARIO INT NOT NULL,
TOKEN VARCHAR (255)NOT NULL UNIQUE,
DATA_SOLICITACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
DATA_EXPEDICAO DATETIME NOT NULL,
ULTILIZADO BOOL NOT NULL DEFAULT FALSE,
FK_CADASTRO_RECUPERA INT NOT NULL,
CONSTRAINT  FK_CADASTRO_RECUPERA FOREIGN KEY (FK_CADASTRO_RECUPERA)
REFERENCES USUARIO_CADASTRO(ID_USUARIO),
CONSTRAINT FK_SENHA_USUARIO FOREIGN KEY(RECUPERA_SENHA_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE CASCADE
ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS DADOS(
ID_DADOS INT AUTO_INCREMENT PRIMARY KEY,
FK_DADOS_USUARIO INT NOT NULL,
CONSTRAINT FK_DADOS_USUARIO FOREIGN KEY(FK_DADOS_USUARIO)
REFERENCES USUARIO_CADASTRO(ID_USUARIO)
 
);
CREATE TABLE IF NOT EXISTS PAGAMENTO_ENTRADA(
ID_ENTRADA INT PRIMARY KEY,
FK_ID_USUARIO INT  NOT NULL,
DIA_HORA_ACESSO DATETIME DEFAULT CURRENT_TIMESTAMP,
DATA_PERVISTA_ENTRADA DATE ,
DATA_REAL_ENTRADA DATE NOT NULL,
EMPRESTIMO_ENTRADA TINYINT NOT NULL,
ENTRADA_DEBITO DECIMAL (10,2),
ENTRADA_PIX DECIMAL(10,2),
ENTRADA_DINHEIRO DECIMAL(10,2),
DESCRICAO_ENTRADA TEXT NULL,
-- AS FKS DA TABELA ENTRADA
 FOREIGN KEY(FK_ID_USUARIO) REFERENCES USUARIO_CADASTRO(ID_USUARIO)
ON DELETE RESTRICT #RESTRINGINDO 
ON UPDATE CASCADE );


CREATE TABLE IF NOT EXISTS DINHEIRO(
ID_DINHEIRO INT AUTO_INCREMENT PRIMARY KEY,
FK_DINHEIRO_ENTRADA INT NOT NULL,
VALOR_COMPRA_DINHEIRO DECIMAL(10,2),
DATA_PAGAMENTO_DINHEIRO DATE NOT NULL,
DESCRICAO_PAGAMENTO_DINHEIRO TEXT,
CONSTRAINT FK_DEBITO_ENTRADA FOREIGN KEY(FK_DINHEIRO_ENTRADA)
REFERENCES PAGAMENTO_ENTRADA(ID_ENTRADA));

CREATE TABLE IF NOT EXISTS DEBITO(
ID_DEBITO INT AUTO_INCREMENT PRIMARY KEY,
FK_ENTRADA INT NOT NULL,
NOME_CARTAO_DEBITO VARCHAR(20) NOT NULL,
NUMERO_CONTA_DEBITO INT NOT NULL UNIQUE,
VALOR_CARTAO_DEBITO DECIMAL(10,2)NOT NULL,
VALOR_DEBITO_PIX DECIMAL(10,2)NOT NULL,
VALOR_BOLETO DECIMAL(10,2)NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
DESCRICAO_PAGO_DEBITO TEXT,
CONSTRAINT FK_ENTRADA FOREIGN KEY(FK_ENTRADA)
REFERENCES PAGAMENTO_ENTRADA(ID_ENTRADA));

CREATE TABLE IF NOT EXISTS CARTAO_CREDITO(
ID_CREDITO INT AUTO_INCREMENT PRIMARY KEY ,
FK_DEBITO INT NOT NULL,
NOME_CARTAO_CREDITO VARCHAR(20) NOT NULL,
NUMERO_CARTAO_CREDITO VARCHAR(20) NOT NULL UNIQUE,
VALOR_COMPRA_CREDITO DECIMAL(10,2) NOT NULL,
DATA_PAGAMENTO_CREDITO DATE NOT NULL,	
DESCRICAO_PAGAMENTO_CREDITO TEXT,
CONSTRAINT CREDITO_DEBITO FOREIGN KEY(FK_DEBITO)
REFERENCES DEBITO (ID_DEBITO));

CREATE TABLE IF NOT EXISTS  FORMA_PAGAMENTO(
ID_FORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_PAGAMENTO VARCHAR(20),
FK_DEBITO INT NOT NULL,
FK_DINHEIRO INT NOT NULL, 
CONSTRAINT FK_DINHEIRO FOREIGN KEY (FK_DINHEIRO)
REFERENCES DINHEIRO(ID_DINHEIRO),
CONSTRAINT FK_DEBITO FOREIGN KEY(FK_DEBITO)
REFERENCES DEBITO(ID_DEBITO),
FK_CARTAO_CREDITO INT NOT NULL,
CONSTRAINT FK_CARTAO_CREDITO FOREIGN KEY (FK_CARTAO_CREDITO)
REFERENCES CARTAO_CREDITO(ID_CREDITO)
);
CREATE TABLE IF NOT EXISTS PARCELAS(
ID_PARCELAS INT AUTO_INCREMENT PRIMARY KEY,
MES_REFERENCIA_PARCELA DATE NOT NULL,
VALOR_PARCELA DECIMAL(10,2) NOT NULL,
NUMERO_PARCELA INT NOT NULL,
TOTAL_PARCELA INT NOT NULL,
STATUS_PARCELAS  VARCHAR(20),
DESCRICAO_PARCELA TEXT,
CREDITO_PARCELAS INT,
CONSTRAINT CREDITO_PARCELAS FOREIGN KEY (CREDITO_PARCELAS)
REFERENCES CARTAO_CREDITO (ID_CREDITO)
);

CREATE TABLE IF NOT EXISTS SAIDA(
ID_SAIDA INT AUTO_INCREMENT PRIMARY KEY,
PAGAMENTO_SAIDA INT,
VALOR_SAIDA DECIMAL(10,2) NOT NULL,
TIPO_GASTO_SAIDA VARCHAR (100) NOT NULL,
DATA_PAGAMENTO_SAIDA DATE NOT NULL,
CONSTRAINT PAGAMENTO_SAIDA FOREIGN KEY (PAGAMENTO_SAIDA)
REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);
CREATE TABLE IF NOT EXISTS METAS(
ID_META INT auto_increment primary KEY,
VALOR_META DECIMAL(10,2) NOT NULL,
VALOR_TOTAL_META DECIMAL(10,2) NOT NULL,
CONTRIBUICAO_MENSAL_META DECIMAL (10,2) NOT NULL,
MES_META DATE NOT NULL,
FORMA_META INT,
 CONSTRAINT FORMA_META FOREIGN KEY (FORMA_META)
 REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)

);

 /* ------------------------create view do banco de dados representado os dados pessoais de perfil do do usuario -------------------------------*/

 CREATE VIEW INFORMACOES_PESSOAIS AS
SELECT 
  
    NOME_USUARIO,
    CADASTRO_NOME_COMPLETO AS NOME_REAL,
    CADASTRO_NASC,
    TIMESTAMPDIFF(YEAR, CADASTRO_NASC, CURDATE()) AS IDADE,
    PAIS,
    ESTADO
FROM USUARIO_CADASTRO;

/* -------------view de pesquisar --do banco  de dados----------*/

CREATE VIEW PESQUISAR AS
SELECT 
    pe.ID_ENTRADA,
    pe.FK_ID_USUARIO,
    pe.DIA_HORA_ACESSO,
    pe.DATA_PERVISTA_ENTRADA,
    pe.DATA_REAL_ENTRADA,
    pe.EMPRESTIMO_ENTRADA,
    pe.ENTRADA_DEBITO,
    pe.ENTRADA_PIX,
    pe.ENTRADA_DINHEIRO,
    pe.DESCRICAO_ENTRADA,

    di.ID_DINHEIRO,
    di.VALOR_COMPRA_DINHEIRO,
    di.DATA_PAGAMENTO_DINHEIRO,
    di.DESCRICAO_PAGAMENTO_DINHEIRO,

    de.ID_DEBITO,
    de.NOME_CARTAO_DEBITO,
    de.NUMERO_CONTA_DEBITO,
    de.VALOR_CARTAO_DEBITO,
    de.VALOR_DEBITO_PIX,
    de.VALOR_BOLETO,
    de.DATA_PAGAMENTO AS DATA_PAGAMENTO_DEBITO,
    de.DESCRICAO_PAGO_DEBITO,

    cc.ID_CREDITO,
    cc.NOME_CARTAO_CREDITO,
    cc.NUMERO_CARTAO_CREDITO,
    cc.VALOR_COMPRA_CREDITO,
    cc.DATA_PAGAMENTO_CREDITO,
    cc.DESCRICAO_PAGAMENTO_CREDITO,

    fp.ID_FORMA_PAGAMENTO,
    fp.TIPO_PAGAMENTO,

    pa.ID_PARCELAS,
    pa.MES_REFERENCIA_PARCELA,
    pa.VALOR_PARCELA,
    pa.NUMERO_PARCELA,
    pa.TOTAL_PARCELA,
    pa.STATUS_PARCELAS,
    pa.DESCRICAO_PARCELA,

    sa.ID_SAIDA,
    sa.VALOR_SAIDA,
    sa.TIPO_GASTO_SAIDA,
    sa.DATA_PAGAMENTO_SAIDA,

    me.ID_META,
    me.VALOR_META,
    me.VALOR_TOTAL_META,
    me.CONTRIBUICAO_MENSAL_META,
    me.MES_META

FROM PAGAMENTO_ENTRADA pe
LEFT JOIN DINHEIRO di 
    ON di.FK_DINHEIRO_ENTRADA = pe.ID_ENTRADA
LEFT JOIN DEBITO de 
    ON de.FK_ENTRADA = pe.ID_ENTRADA
LEFT JOIN CARTAO_CREDITO cc 
    ON cc.FK_DEBITO = de.ID_DEBITO
LEFT JOIN FORMA_PAGAMENTO fp 
    ON fp.FK_DEBITO = de.ID_DEBITO
    AND fp.FK_DINHEIRO = di.ID_DINHEIRO
    AND fp.FK_CARTAO_CREDITO = cc.ID_CREDITO
LEFT JOIN PARCELAS pa
    ON pa.CREDITO_PARCELAS = cc.ID_CREDITO
LEFT JOIN SAIDA sa
    ON sa.PAGAMENTO_SAIDA = fp.ID_FORMA_PAGAMENTO
LEFT JOIN METAS me
    ON me.FORMA_META = fp.ID_FORMA_PAGAMENTO;



